CREATE TABLE IF NOT EXISTS users (
    ID UUID NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT true,

    UNIQUE(email)
)